/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frc.team5163.gui;

import frc.team5163.Dashboard;
import frc.team5163.img.ImgOverlay;
import frc.team5163.vis.VisionDisabled;
import frc.team5163.vis.VisionHW;
import frc.team5163.vis.VisionSemiManual;

/**
 *
 * @author Rish Shadra <rshadra@gmail.com>
 */
public class VisionInfoWindow extends javax.swing.JFrame {

    /**
     * Creates new form TargetInfo
     */
    public VisionInfoWindow() {
        initComponents();
        disableLMRButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        distLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        radioDisable = new javax.swing.JRadioButton();
        radioSemiManual = new javax.swing.JRadioButton();
        radioHW = new javax.swing.JRadioButton();
        radioLMR = new javax.swing.JRadioButton();
        buttonLeft = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();
        buttonMid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Target Information");

        xLabel.setText("X:");

        yLabel.setText("Y:");

        distLabel.setText("Distance:");

        jLabel2.setText("Targeting Method");

        buttonGroup2.add(radioDisable);
        radioDisable.setText("Disable");
        radioDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDisableActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioSemiManual);
        radioSemiManual.setText("Semi-Manual");
        radioSemiManual.setEnabled(false);
        radioSemiManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSemiManualActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioHW);
        radioHW.setSelected(true);
        radioHW.setText("H/W Ratio");
        radioHW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHWActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioLMR);
        radioLMR.setText("L/M/R");
        radioLMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLMRActionPerformed(evt);
            }
        });

        buttonLeft.setText("L");
        buttonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftActionPerformed(evt);
            }
        });

        buttonRight.setText("R");
        buttonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightActionPerformed(evt);
            }
        });

        buttonMid.setText("M");
        buttonMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioHW)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioLMR)
                            .addComponent(radioSemiManual)
                            .addComponent(radioDisable)
                            .addComponent(xLabel)
                            .addComponent(yLabel)
                            .addComponent(distLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonLeft)
                                .addGap(18, 18, 18)
                                .addComponent(buttonMid)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRight))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xLabel)
                .addGap(1, 1, 1)
                .addComponent(yLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distLabel)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioDisable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSemiManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioHW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioLMR)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLeft)
                    .addComponent(buttonMid)
                    .addComponent(buttonRight))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDisableActionPerformed
        disableLMRButtons();
        setDisabled();
    }//GEN-LAST:event_radioDisableActionPerformed

    private void buttonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftActionPerformed

    }//GEN-LAST:event_buttonLeftActionPerformed

    private void radioLMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLMRActionPerformed
        enableLMRButtons();
    }//GEN-LAST:event_radioLMRActionPerformed

    private void buttonMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMidActionPerformed

    }//GEN-LAST:event_buttonMidActionPerformed

    private void buttonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightActionPerformed

    }//GEN-LAST:event_buttonRightActionPerformed

    private void radioHWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHWActionPerformed
        disableLMRButtons();
        setHW();
    }//GEN-LAST:event_radioHWActionPerformed

    private void radioSemiManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSemiManualActionPerformed
        disableLMRButtons();
    }//GEN-LAST:event_radioSemiManualActionPerformed

    private void disableLMRButtons() {
        buttonLeft.setEnabled(false);
        buttonMid.setEnabled(false);
        buttonRight.setEnabled(false);
    }

    private void enableLMRButtons() {
        buttonLeft.setEnabled(true);
        buttonMid.setEnabled(true);
        buttonRight.setEnabled(true);
    }
    
    public void setDisabled() {
        ImgOverlay.clearCustom();
        radioDisable.setSelected(true);
        Dashboard.getCameraWindow().setVisionProvider(new VisionDisabled());
    }
    
    public void setSemiManual(int x, int y) {
        radioSemiManual.setSelected(true);
        Dashboard.getCameraWindow().setVisionProvider(new VisionSemiManual(x, y));
    }
    
    public void setHW() {
        ImgOverlay.clearCustom();
        radioHW.setSelected(true);
        Dashboard.getCameraWindow().setVisionProvider(new VisionHW());
    }
    
    public void setLMR() {
        ImgOverlay.clearCustom();
        radioLMR.setSelected(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisionInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisionInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisionInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisionInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisionInfoWindow().setVisible(true);
            }
        });
    }

    public void update(boolean valid, int x, int y, double distance) {
        //validityLabel.setText(Boolean.toString(valid));
        xLabel.setText("X: " + Integer.toString(x));
        yLabel.setText("Y: " + Integer.toString(y));
        distLabel.setText(Double.toString(distance));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonMid;
    private javax.swing.JButton buttonRight;
    private javax.swing.JLabel distLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioDisable;
    private javax.swing.JRadioButton radioHW;
    private javax.swing.JRadioButton radioLMR;
    private javax.swing.JRadioButton radioSemiManual;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel yLabel;
    // End of variables declaration//GEN-END:variables
}
